---
- name: Install and configure Docker
  hosts: all
  become: true

  tasks:
    - name: Update package lists
      yum: update_cache=yes

    - name: Create directory for Docker key
      file:
        path: /etc/yum.repos.d/
        state: directory
        mode: 0755

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/centos/gpg
        dest: /etc/yum.repos.d/docker.asc
        mode: 0644

    - name: Install dnf-plugins-core for adding repositories
      shell: dnf install dnf-plugins-core
      register: dnf_install

    - name: Add Docker repository
      shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: dnf_install.rc == 0  # Only run if previous step succeeded

    - name: Install Docker package
      package:
        name: docker-ce
        state: latest
      when: dnf_install.rc == 0  # Only run if previous steps succeeded

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group 
      user:
        name: centos
        groups: docker
        append: yes
      