---
- name: Install and configure Docker (CentOS)
  hosts: all
  become: true  # Needs root privileges

  tasks:
    - name: Update package lists
      yum: update_cache=yes

    - name: Install prerequisites
      yum:
        name:
          - ca-certificates
          - curl

    - name: Create directory for Docker key
      file:
        path: /etc/yum.repos.d/
        state: directory
        mode: 0755

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/centos/gpg
        dest: /etc/yum.repos.d/docker.asc
        mode: 0644

    - name: Add repository for Docker
      copy:
        content: |
          [docker-ce]
          name=Docker CE Stable
          baseurl=https://download.docker.com/linux/centos/{{ ansible_distribution_major }}/stable
          gpgcheck=1
          gpgkey=file:///etc/yum.repos.d/docker.asc
        dest: /etc/yum.repos.d/docker.repo

    - name: Update package lists again
      yum: update_cache=yes

    - name: Install Docker and related packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      debug:
        msg:
          - Docker version is {{ docker_version.version }}

    - name: Install Node.js
      apt:
        name: nodejs

    - name: Verify Node.js installation
      debug:
        msg:
          - Node.js version is {{ node_version }}
          
          