---
- name: Install and configure Docker
  hosts: all
  become: true

  tasks:
    - name: Update package lists
      yum: update_cache=yes

    - name: Create directory for Docker key
      file:
        path: /etc/yum.repos.d/
        state: directory
        mode: 0755

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/centos/gpg
        dest: /etc/yum.repos.d/docker.asc
        mode: 0644
        
    - name: Add Docker repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     
    - name: Install Docker package
      yum:
        name: docker-ce
        state: latest
  
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group 
      user:
        name: centos
        groups: docker
        append: yes
      