---
- name: Install and configure NodeJS and Docker
  hosts: localhost
  become: true
  vars:
    arch_mapping:
      x86_64: amd64
      aarch64: arm64

  tasks:
    # Gather facts about the system
    - name: Get system facts
      setup:

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Node.js
      apt:
        name: nodejs

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl

    - name: Create directory for Docker key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644

    - name: Add Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update package lists again
      apt: 
        update_cache: yes

    - name: Install Docker engine
      apt:
        name: docker.io
        state: present
        
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
