---
- name: Install and configure Docker
  hosts: localhost
  become: true
  vars:
    arch_mapping:
      x86_64: amd64
      aarch64: arm64

  tasks:
    # Gather facts about the system
    - name: Get system facts
      setup:

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl

    - name: Create directory for Docker key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644

    - name: Add repository for Docker
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch={{ arch_mapping[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_version }} stable"
        create: yes

    - name: Update package lists again
      apt:
        update_cache: yes

    - name: Install Docker and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      debug:
        msg:
          - Docker version is {{ docker_version.version }}

    - name: Install Node.js
      apt:
        name: nodejs

    - name: Verify Node.js installation
      debug:
        msg:
          - Node.js version is {{ node_version }}
          
          