---
- name: Install and configure Docker
  hosts: all
  become: true  # Needs root privileges

  tasks:
    - name: Update package lists
      apt: update_cache=yes

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl

    - name: Create directory for Docker key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644

    - name: Add repository for Docker
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch={{ ansible_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_codename }} stable"
        create: yes

    - name: Update package lists again
      apt: update_cache=yes

    - name: Install Docker and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Run Hello World container
      docker:
        name: hello-world
        image: hello-world


