---
- hosts: all
  become: true  
  tasks:
    - name: Update package lists
      yum: name=* state=latest  
      
    - name: Install Docker dependencies
      package:
        name:
          - docker-ce
          - docker-compose  

    - name: Add Docker user group
      group:
        name: docker
        state: present

    - name: Add current user to Docker group (Optional)
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
        state: present  

    - name: Install Node.js and npm using yum
      yum:
        name:
          - nodejs  
        state: present

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker and Node.js installations
      debug:
        msg:
          - Docker version is {{ docker_version.version }}
          - Node.js version is {{ node_version.version }}  
      register: version_info  
